# dbt_project.yml

name: 'dbt_data_pipeline'
version: '1.0.0'

profile: 'dbt_data_pipeline'

model-paths: ["dbt_data_pipeline/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_data_pipeline:
    datalake:
      +schema: dp_lake    # Crée des tables dans le dataset dp_lake pour la couche lake
      +materialized: table
    datahub:
      +schema: hub     # Crée des tables dans le dataset dp_hub pour la couche hub
      +materialized: view
    dataproducts:
      +schema: dataproducts  # Crée des tables dans le dataset dp_dataproducts pour la couche dataproducts
      +materialized: table
